env:
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  'prettier/prettier': warn
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: after-used
      ignoreRestSiblings: false
  'no-console': 'warn'
  import/no-unused-modules:
    - warn
    - unusedExports: true
